<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LTSSENTHIV" name="com.tractiondigital.SuiteTestingForm.SuiteTestingFormValidDataTest" tests="3" failures="1" timestamp="04 Jun 2018 06:36:55 GMT" time="22.109" errors="0">
  <testcase name="SuiteTestingFormValidDataTestPOM" time="6.973" classname="com.tractiondigital.SuiteTestingForm.SuiteTestingFormValidDataTest"/>
  <testcase name="SuiteTestingFormValidDataTestPOM" time="6.716" classname="com.tractiondigital.SuiteTestingForm.SuiteTestingFormValidDataTest"/>
  <testcase name="SuiteTestingFormValidDataTestPOM" time="8.420" classname="com.tractiondigital.SuiteTestingForm.SuiteTestingFormValidDataTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	
SuiteTestingFormValidDataTest:- Testing Form confirmation Message actual: &#039;&#039; is not matched with expected &#039;Thank you for entering the competition.&#039;,
	
SuiteTestingFormInValidData  --&gt; &#039;FAIL&#039;">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

SuiteTestingFormValidDataTest:- Testing Form confirmation Message actual: '' is not matched with expected 'Thank you for entering the competition.',

SuiteTestingFormInValidData  --> 'FAIL'
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.tractiondigital.SuiteTestingForm.SuiteTestingFormValidDataTest.SuiteTestingFormValidDataTestPOM(SuiteTestingFormValidDataTest.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SuiteTestingFormValidDataTestPOM -->
</testsuite> <!-- com.tractiondigital.SuiteTestingForm.SuiteTestingFormValidDataTest -->
